apiVersion: apps/v1
kind: Deployment
metadata:
  name: thrift-server
  namespace: dubbo-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thrift-server
  template:
    metadata:
      labels:
        app: thrift-server
    spec:
      containers:
        - name: thrift-server
          image: 15841721425/thrift-server:1.3  # 更换为你的镜像路径
          imagePullPolicy: Always
          ports:
            - name: thrift-port
              containerPort: 40001
            - name: health-port
              containerPort: 40002  # 假定为Thrift服务器的健康检查端口
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: thrift-server-service
  namespace: dubbo-benchmark
spec:
  selector:
    app: thrift-server
  ports:
    - protocol: TCP
      port: 40001
      targetPort: 40001
  type: ClusterIP
