apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-claim
  namespace: dubbo-benchmark
spec:
  storageClassName: alicloud-disk-essd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
