spring:
  application:
    # ===服务名===
    name: springcloud-server
  cloud:
    nacos:
      discovery:
        # =====服务的ip地址======
        server-addr: ${NACOS_ADDRESS:121.250.209.74}:8848
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:121.250.209.74}:5432/benchmark
    username: admin
    password: cong0917

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false   # 关闭驼峰转下划线
  global-config:
    db-config:
      update-strategy: ignored # null也会更新
server:
  port: 60080

