apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: dubbo-benchmark
  labels:
    app: nacos
spec:
  ports:
    - name: http-port
      port: 8848
      targetPort: 8848
    - name: grpc-port
      port: 9848
      targetPort: 9848
  selector:
    app: nacos
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: dubbo-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:latest
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - name: http-port
              containerPort: 8848
            - name: grpc-port
              containerPort: 9848
          env:
            - name: MODE
              value: "standalone"
