name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "dubbo-kryo","dubbo-fst" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Start server
        run: ./benchmark.sh ${{ matrix.target }}-server &
      - name: Wait server ready
        run: sleep 20
      - name: Run benchmark
        run: ./benchmark.sh -a "--warmupIterations=1 --warmupTime=1 --measurementIterations=1 --measurementTime=1" ${{ matrix.target }}-client > output.txt
      - name: Kill jobs
        run: jobs -p | xargs kill
      - name: Save output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-output
          path: output.txt
